# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  docker-build:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      NO_COLOR: TRUE
      JFROG_CLI_LOG_LEVEL: DEBUG
    steps:
      - run:
          name: install cli 
          command: curl -fL https://install-cli.jfrog.io | sh
      - run:
          name: cli config
          command: jf config add jfrog-test --url=https://ecosysjfrog.jfrog.io/ --password=${JF_PLATFORM_PASS} --user=assafa
      - run:
          name: docker pull
          command: docker pull nginx:latest
      - run:
          name: docker scan
          command: jf docker scan nginx:latest --format=table

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - docker-build
